language: haxe

haxe:
  - "3.1.3"
  - "3.2.0"
  - development

neko: "2.0.0"

services:
  - mongodb

install:
  - haxelib dev mongodb $TRAVIS_BUILD_DIR
  - haxelib install hxcpp
  - haxelib install utest

matrix:
  fast_finish: true
  allow_failures:

hxml:
  - test.hxml
